name: issues workflow
on:
  workflow_dispatch:
  issues:
jobs:
  handle-issues:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub context issues
        run: |
          echo "Event information"
          echo "${{ toJson(github.event) }}"